// src/components/tabs/Autumn.svelte
<script>
	import { TabPane } from 'sveltestrap';
	import Season from '../aggregates/Season.svelte';
	import { AUTUMN, WINTER, BREEDING } from '../../lib/constants';
	import { getMonthsOfRecords } from '../../lib/data-tools';
	import ContentOrSettings from '../UI/ContentOrSettings.svelte';

	import {
		throughput,
		findLateRecords,
		findEarlyRecords
	} from '../../lib/migration';

	/** @typedef {import('../../lib/data-tools').Record} Record*/
	/** @typedef {import('../../lib/data-tools').Stat} Stat*/
	/** @typedef {import('../../lib/settings').Settings} Settings*/

	/** @type {Record[]} */
	export let records = [];
	/** @type {Settings} */
	export let settings;
	/** @type {string[]} */
	export let breedingSites;
	export let bird;
	/**
	 * @param {Record[]} records
	 * @param {string[]} breedingSites
	 * @return {Stat[]}
	 */
	const getPreStats = (records, breedingSites) => {
		if (settings[BREEDING] > 2) return [];

		return [
			{
				heading: settings[BREEDING] > 0 ? 'Earliest non breeding' : 'Earliest',
				content: {
					records: findEarlyRecords(
						records.filter(({ location }) => !breedingSites.includes(location))
					),
					viewMoreHeading: 'Other early records'
				}
			}
		];
	};

	/**
	 * @param {Record[]} records
	 * @return {Stat[]}
	 */
	const getPostStats = (records) => {
		const stats = [];
		if (!(settings[BREEDING] > 2 || settings[WINTER] > 2)) {
			stats.push(...throughput(records));
		}
		if (settings[WINTER] <= 0) {
			stats.push({
				heading: 'Latest',
				content: {
					records: findLateRecords(records),
					viewMoreHeading: 'Other late records'
				}
			});
		}

		return stats;
	};
	/**
	 * @param {Settings} settings
	 * @return {number[]}
	 */
	const getPassageMonths = (settings) => {
		const passageMonths = [7, 8, 9, 10];
		if (settings[BREEDING] < 3) {
			passageMonths.unshift(6);
		}
		if (settings[WINTER] < 2) {
			passageMonths.push(11, 12);
		}
		return passageMonths;
	};

	$: passageMonths = getPassageMonths(settings);
	$: relevantRecords = getMonthsOfRecords(records, ...passageMonths);
	$: preStats = getPreStats(relevantRecords, breedingSites);
	$: postStats = getPostStats(relevantRecords);
</script>

<ContentOrSettings {settings} {bird} season={AUTUMN}>
	<Season
		heading="Autumn passage"
		months={passageMonths}
		records={relevantRecords}
		{preStats}
		{postStats}
	/>
</ContentOrSettings>

// src/components/Autumn.jsx
import React from 'react'
import {throughput, getMonthsOfRecords, findLateRecords, findEarlyRecords} from '../lib/data-tools'
import {Season} from './Season'
import { Record} from './Records'
const getEarlies = ({records, distribution, breedingSites}) => {
	if (distribution.breeding > 2) return null
	const earlies = findEarlyRecords(records.filter(({location}) => !breedingSites.includes(location)))
	return {
		heading: distribution.breeding ? 'Earliest non breeding' : 'Earliest',


  content: <Record {...earlies} viewMoreHeading="View other early records"/>

}
}

const getLates = ({records, distribution}) => {
	if (distribution.winter) return null
	const latest = findLateRecords(records)
	return {heading: 'Latest',
  content: <Record {...latest} viewMoreHeading="View other late records" />
}
}

const estimateThroughput = ({records, distribution}) => {
	return !(distribution.breeding > 2 || distribution.winter > 2) ?  {
		heading: 'Estimated total throughput',
		content: <ul>
			{Object.entries(throughput(records)).map(([name, value]) => <li><breeding>{name}</breeding>: {value}</li>)}
		</ul>
	} : null
}


export const Autumn = ({records, distribution, breedingSites}) => {
	breedingSites = breedingSites.map(({location}) => location)
	const passageMonths = [7, 8, 9, 10]
	if (distribution.breeding < 3) {
		passageMonths.unshift(6)
	}
	if (!distribution.winter < 2) {
		passageMonths.push(11, 12)
	}

	records = getMonthsOfRecords(records, ...passageMonths)

	return (
  <Season
    heading="Autumn passage"
    months={passageMonths}
    records={records}
    preContent={
    	[getEarlies({
    		records,
    		distribution,
    		breedingSites
    	})]
    }
    postContent={
			[estimateThroughput({records, distribution}),getLates({
    		records,
    		distribution,
    	})]
}
  />
)
}
