// src/components/aggregates/Entry.svelte
<script>
	import { Table } from 'sveltestrap';
	import NotableRecords from './NotableRecords.svelte';
	import Records from './Records.svelte';
	import Record from './Record.svelte';
	import { group, getOutliers, sortPropDesc } from '../../lib/data-tools';

	/** @typedef {import('../../lib/data-tools').Record} Record */
	/** @typedef {import('../../lib/data-tools').AggregateRecord} AggregateRecord */

	/** @type {Record[]} */
	export let records;
	export let preStats = [];
	export let postStats = [];

	/**
	 * @param {Record[]} records
	 * @returns {number}
	 */
	const getNumberOfSites = (records) => {
		const sites = new Set();
		records.forEach(({ location }) => sites.add(location));
		return [...sites].length;
	};

	/**
	 * @param {Record[]} records
	 * @returns {number}
	 */
	const countRecords = (records) => records.length;

	/**
	 * @param {Record[]} records
	 * @returns {number}
	 */
	const countBirds = (records) =>
		records.reduce((sum, { numberIndex }) => sum + numberIndex, 0);

	/**
	 * @param {Record[]} records
	 * @returns {AggregateRecord}
	 */
	const aggregate = (records) => {
		records = [...records].sort(sortPropDesc('numberIndex'));
		const maxNumberIndex = records[0].numberIndex;
		const occasions = records.filter(
			({ numberIndex }) => numberIndex === maxNumberIndex
		);

		return {
			...records[0],
			...(occasions.length > 1
				? {
						dates: occasions.map(({ date }) => date),
						locations: occasions.map(({ location }) => location)
				  }
				: {}),
			records: getOutliers(records, 'numberIndex')
		};
	};
	/**
	 * @param {function} func
	 * @returns {(records: Record[]) => AggregateRecord}
	 */
	const aggregateByDay = (func) => (records) => {
		records = group(records, ({ date }) => date.toISOString())
			.map((records) => ({
				records,
				date: records[0].date,
				numberIndex: func(records)
			}))
			.sort(sortPropDesc('numberIndex'));

		if (!records.length) {
			return {
				numberIndex: 0,
				records: []
			};
		}
		return aggregate(records);
	};

	let stats = [...preStats];

	if (records.length) {
		const maxCitywideDayCount = aggregateByDay(countBirds)(records);

		const numberOfSites = getNumberOfSites(records);
		const highSingleSiteCounts = getOutliers(records, 'numberIndex');

		stats.push({ heading: 'Number of sites', content: numberOfSites });
		if (numberOfSites > 1) {
			stats.push({
				heading: 'Max citywide sites in day',
				component: Record,
				content: {
					...aggregateByDay(countRecords)(records),
					viewMoreHeading: 'View other high counts'
				}
			});
		}
		if (maxCitywideDayCount.numberIndex > 1) {
			stats.push({
				heading: 'Max citywide day count',
				component: Record,
				content: {
					...maxCitywideDayCount,
					viewMoreHeading: 'View other high counts'
				}
			});
		}

		if (highSingleSiteCounts[0].numberIndex > 1) {
			stats.push({
				heading: 'High single site counts',
				component: NotableRecords,
				content: {
					records: highSingleSiteCounts,
					viewMoreHeading: 'View other high counts'
				}
			});
		}
	}
	$: stats.push(...postStats);
</script>

<Table>
	<tbody>
		{#each stats as stat}
			<tr>
				<th>{stat.heading}</th>
				<td
					>{#if stat.component}<svelte:component
							this={stat.component}
							{...stat.content}
						/>{:else}{stat.content}{/if}</td
				>
			</tr>
		{/each}
	</tbody>
</Table>

<Records {records} viewMoreHeading="View all records" />

<style>
	th {
		min-width: 100px;
	}
</style>

// src/components/Entry.jsx
import React from 'react'
import {Card, Button, Accordion, Table} from 'react-bootstrap'
import {group, getOutliers, sortPropDesc} from '../lib/data-tools'
import {Records, Record} from './Records'

const getNumberOfSites = records => {
	const sites = new Set()
	records.forEach(({location}) => sites.add(location))
	return [...sites].length
}

const aggregate = records => {
	records = [...records].sort(sortPropDesc('numberIndex'))
	const maxNumberIndex = records[0].numberIndex
	const occasions = records.filter(({numberIndex}) => numberIndex === maxNumberIndex)

	return {
		...records[0],
		...(occasions.length > 1 ? {
			dates: occasions.map(({date}) => date),
			locations: occasions.map(({location}) => location)
		} : {}),
		records: getOutliers(records, 'numberIndex')
	}
}

const aggregateByDay = (func) => (records) => {

	records = group(records, ({date}) => date.toISOString())
		.map(records => ({
			records,
			date: records[0].date,
			numberIndex: func(records)
		}))
		.sort(sortPropDesc('numberIndex'))

		if (!records.length) {
			return {
				numberIndex: 0,
				records: []
			}
		}
		return aggregate(records)
}

const EntryCard = ({heading, body}) => (
  <Card>
    <Card.Header>
      {heading}
    </Card.Header>
    {body ? <Card.Body>{body}</Card.Body> : null}
  </Card>
)

const AccordionEntryCard = ({heading, body, eventKey}) => body ? (
  <Card>
    <Card.Header>
      <Accordion.Toggle as={Button} variant="link" eventKey={eventKey}>
        {heading}
      </Accordion.Toggle>
    </Card.Header>
    <Accordion.Collapse eventKey={eventKey}>
      <Card.Body>{body}</Card.Body>
    </Accordion.Collapse>
  </Card>
) : <EntryCard heading={heading} />


const TableRow = ({heading, content}) => (
  <tr>
    <th style={{minWidth: '100px'}}>{heading}</th>
    <td>{content}</td>
  </tr>
)

const MaxOrForgetIt = ({aggregate, threshold = 1}) => {
  return aggregate.numberIndex > threshold ? <Record {...aggregate} /> : <div>Nothing of note</div>;
}

export const Entry = ({allowEmpty = false, heading, records, isAccordion = false, index,
  preContent = [], postContent = []}) => {
	if (!records.length) {
		return allowEmpty  ?  <EntryCard heading={heading} body={null} />: null
	}

  const maxCitywideDayCount = aggregateByDay(
records => records.reduce((sum, {numberIndex}) => sum + numberIndex, 0)
  )(records);

  const numberOfSites = getNumberOfSites(records);
  const highSingleSiteCounts = getOutliers(records, 'numberIndex');
	const body = (
  <>

    <Table>
      <tbody>
        {preContent.map(props => <TableRow {...props} />)}
        <TableRow
          heading="Number of sites"
          content={numberOfSites}
        />
        {numberOfSites > 1 ? <TableRow
          heading="Max citywide sites in day"
          content={(
            <Record {...aggregateByDay(
records => records.length
  )(records)} viewMoreHeading="View other high counts"
            />
)}
        /> : null}
        { maxCitywideDayCount.numberIndex > 1 ? <TableRow
          heading="Max citywide day count"
          content={(
            <Record {...maxCitywideDayCount} viewMoreHeading="View other high counts"
            />
)}
        /> : null}

        {highSingleSiteCounts[0].numberIndex > 1 ? <TableRow
          heading="High single site counts"
          content={<>
            <Record {...highSingleSiteCounts[0]} />
            <Records records={highSingleSiteCounts.slice(1)} heading="View other high counts"/>
           </>}
        /> : null}
        {postContent.map(props => <TableRow {...props} />)}

      </tbody>
    </Table>
    <Records records={records} heading="View all records" />
  </>
)

  const Wrapper = isAccordion ? AccordionEntryCard : EntryCard

	return <Wrapper heading={heading} body={body} eventKey={`${  index}`} />

}
