// src/components/tabs/Winter.svelte
<script>
	import Season from '../aggregates/Season.svelte';
	import { WINTER, BREEDING } from '../../lib/constants';
	import ContentOrSettings from '../UI/ContentOrSettings.svelte';
	/** @typedef {import('../../lib/data-tools').Record} Record*/
	/** @typedef {import('../../lib/bird-settings').Settings} Settings*/

	/** @type {Record[]} */
	export let records;
	/** @type {Settings} */
	export let settings;
	export let bird;

	// If it's springPassage not autumnPassage widespread breeder then we assume
	// winter stretches into March
	$: firstWinterMonths = settings[BREEDING] < 3 ? [1, 2, 3] : [1, 2];
</script>

<ContentOrSettings {settings} {bird} season={WINTER}>
	<Season heading="First winter" months={firstWinterMonths} {records} />
	<Season heading="Second winter" months={[11, 12]} {records} />
</ContentOrSettings>

// src/components/Winter.jsx
import React from 'react'
import {Season} from './Season'
import {getMonthsOfRecords} from '../lib/data-tools'

export const FirstWinter = ({records, distribution}) => {

	// If it'springPassage not autumnPassage widespread breeder then we assume winter stretches
	// into March
	const notWidespreadBreeder = distribution.breeding < 3
	const months = notWidespreadBreeder < 3 ? [1, 2, 3] : [1, 2]
	records = getMonthsOfRecords(records, ...months)
	return <Season heading="First winter" months={months} records={records} />
}

export const SecondWinter = ({records, distribution}) => {
	records = getMonthsOfRecords(records, 11, 12)
	return <Season heading="Second winter" months={[11, 12]} records={records} />
}
