// src/components/SettingsForm.jsx
import React, { useContext} from 'react'
import {Form} from 'react-bootstrap'
import cloneDeep from 'lodash.clonedeep'
import {useLocalStorage} from '../lib/useLocalStorage'

import {UNKNOWN,
 VAGRANT,
 HIGHLY_LOCALISED,
 LOCALISED,
 WIDESPREAD} from '../constants'

const WINTER = 'winter'
const SPRING = 'springPassage'
const BREEDING = 'breeding'
const AUTUMN = 'autumnPassage'

const Dropdown = ({value, species, season, setDistribution, distribution}) => {

  const updateSpecies = (event) => {
    const value = Number(event.target.value)
    if (isNaN(value)) {
      const clone = {...distribution}
      delete clone[season]
      setDistribution(clone)
    } else {
      setDistribution({...distribution, [season]: value})
    }

  }

  return (
    <Form.Control as="select" value={value} onChange={updateSpecies}>
      <option value={null}>Please select</option>
      <option value={UNKNOWN}>UNKNOWN</option>
      <option value={VAGRANT}>VAGRANT</option>
      <option value={HIGHLY_LOCALISED}>HIGHLY_LOCALISED</option>
      <option value={LOCALISED}>LOCALISED</option>
      <option value={WIDESPREAD}>WIDESPREAD</option>
    </Form.Control>
)
 }

export const SettingsForm = ({species, distribution, setDistribution}) => {

  const {winter, springPassage, breeding, autumnPassage} = distribution

  return (
    <Form.Group>
      <h2>{species}</h2>
      <Form.Label>Winter</Form.Label>
      <Dropdown value={winter} species={species} setDistribution={setDistribution} distribution={distribution} season="winter" />
      <Form.Label>Spring passage</Form.Label>
      <Dropdown value={springPassage} species={species} setDistribution={setDistribution} distribution={distribution} season="springPassage" />
      <Form.Label>Breeding</Form.Label>
      <Dropdown value={breeding} species={species} setDistribution={setDistribution} distribution={distribution} season="breeding" />
      <Form.Label>Autumn passage</Form.Label>
      <Dropdown value={autumnPassage} species={species} setDistribution={setDistribution} distribution={distribution} season="autumnPassage" />
    </Form.Group>
)
}

// src/components/UI/SettingsForm.svelte
<script>
	import { getSettingsStore } from '../../lib/bird-settings';
	import { Form, FormGroup, Input, Label } from 'sveltestrap';

	import {
		WINTER,
		SPRING,
		BREEDING,
		AUTUMN,
		UNKNOWN,
		VAGRANT,
		HIGHLY_LOCALISED,
		LOCALISED,
		WIDESPREAD
	} from '../../lib/constants';

	const fields = [
		{
			id: WINTER,
			label: 'Winter'
		},
		{
			id: SPRING,
			label: 'Spring passage'
		},
		{
			id: BREEDING,
			label: 'Breeding'
		},
		{
			id: AUTUMN,
			label: 'Autumn passage'
		}
	];

	export let bird;
	export let season;
	/**
	 * @param {CustomEvent} ev
	 */
	function updateSettings(ev) {
		const target = /** @type {HTMLInputElement} */ (ev.target);
		$settings = { ...$settings, [target.id]: Number(target.value) };
	}

	$: settings = getSettingsStore(bird);

	$: fieldsToOutput = season
		? fields.filter(({ id }) => id === season)
		: fields;
</script>

<Form>
	{#each fieldsToOutput as field}
		<FormGroup>
			<Label for={field.id}>{field.label}</Label>
			<Input
				type="select"
				name={field.id}
				id={field.id}
				value={$settings[field.id]}
				on:change={updateSettings}
			>
				<option value={-1}>Please select</option>
				<option value={UNKNOWN}>UNKNOWN</option>
				<option value={VAGRANT}>VAGRANT</option>
				<option value={HIGHLY_LOCALISED}>HIGHLY_LOCALISED</option>
				<option value={LOCALISED}>LOCALISED</option>
				<option value={WIDESPREAD}>WIDESPREAD</option>
			</Input>
		</FormGroup>
	{/each}
</Form>
